
package com.wellpoint.services.senior.member.wsdl.memberinquiry_v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MemberInquiry-v1_0", targetNamespace = "http://services.wellpoint.com/senior/member/wsdl/MemberInquiry-v1", wsdlLocation = "file:/D:/CareMore%20TFS%20Check/Local%20Tries/wsdl/member/MemberInquiry-v1.wsdl")
public class MemberInquiryV10_Service
    extends Service
{

    private final static URL MEMBERINQUIRYV10_WSDL_LOCATION;
    private final static WebServiceException MEMBERINQUIRYV10_EXCEPTION;
    private final static QName MEMBERINQUIRYV10_QNAME = new QName("http://services.wellpoint.com/senior/member/wsdl/MemberInquiry-v1", "MemberInquiry-v1_0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/CareMore%20TFS%20Check/Local%20Tries/wsdl/member/MemberInquiry-v1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEMBERINQUIRYV10_WSDL_LOCATION = url;
        MEMBERINQUIRYV10_EXCEPTION = e;
    }

    public MemberInquiryV10_Service() {
        super(__getWsdlLocation(), MEMBERINQUIRYV10_QNAME);
    }

    public MemberInquiryV10_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEMBERINQUIRYV10_QNAME, features);
    }

    public MemberInquiryV10_Service(URL wsdlLocation) {
        super(wsdlLocation, MEMBERINQUIRYV10_QNAME);
    }

    public MemberInquiryV10_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEMBERINQUIRYV10_QNAME, features);
    }

    public MemberInquiryV10_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberInquiryV10_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MemberInquiryV10
     */
    @WebEndpoint(name = "MemberInquiryImpl")
    public MemberInquiryV10 getMemberInquiryImpl() {
        return super.getPort(new QName("http://services.wellpoint.com/senior/member/wsdl/MemberInquiry-v1", "MemberInquiryImpl"), MemberInquiryV10.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberInquiryV10
     */
    @WebEndpoint(name = "MemberInquiryImpl")
    public MemberInquiryV10 getMemberInquiryImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.wellpoint.com/senior/member/wsdl/MemberInquiry-v1", "MemberInquiryImpl"), MemberInquiryV10.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEMBERINQUIRYV10_EXCEPTION!= null) {
            throw MEMBERINQUIRYV10_EXCEPTION;
        }
        return MEMBERINQUIRYV10_WSDL_LOCATION;
    }

}
