select CMC_CLCL_CLAIM.CLCL_ID as 'claimId'
,CASE 
		WHEN (CMC_CLCL_CLAIM.CLCL_CUR_STS = 02) THEN 'Paid'
		WHEN (CMC_CLCL_CLAIM.CLCL_CUR_STS = 01) THEN 'Pending Payment'
		WHEN (CMC_CLCL_CLAIM.CLCL_CUR_STS = 15) THEN 'Pended for Review'
		WHEN (CMC_CLCL_CLAIM.CLCL_CUR_STS = 16) THEN 'Pending'
		ELSE CMC_CLCL_CLAIM.CLCL_CUR_STS			
		END AS 'status'
,DATENAME(day, CMC_CLCL_CLAIM.CLCL_LOW_SVC_DT) +'-'+ SUBSTRING(UPPER(DATENAME(month, CMC_CLCL_CLAIM.CLCL_LOW_SVC_DT)), 0,4) +'-'+ DATENAME(year,CMC_CLCL_CLAIM.CLCL_LOW_SVC_DT) AS 'lowServiceDate'		
,DATENAME(day, CMC_CLCL_CLAIM.CLCL_HIGH_SVC_DT) +'-'+ SUBSTRING(UPPER(DATENAME(month, CMC_CLCL_CLAIM.CLCL_HIGH_SVC_DT)), 0,4) +'-'+ DATENAME(year,CMC_CLCL_CLAIM.CLCL_HIGH_SVC_DT) AS 'highServiceDate'
,DATENAME(day, CMC_CLCL_CLAIM.CLCL_PAID_DT) +'-'+ SUBSTRING(UPPER(DATENAME(month, CMC_CLCL_CLAIM.CLCL_PAID_DT)), 0,4) +'-'+ DATENAME(year,CMC_CLCL_CLAIM.CLCL_PAID_DT) AS 'paidDate'
,DATENAME(day, CMC_CLCL_CLAIM.CLCL_RECD_DT) +'-'+ SUBSTRING(UPPER(DATENAME(month, CMC_CLCL_CLAIM.CLCL_RECD_DT)), 0,4) +'-'+ DATENAME(year,CMC_CLCL_CLAIM.CLCL_RECD_DT) AS 'receivedDate'
,CMC_CLCL_CLAIM.CLCL_TOT_CHG as 'totalCharge'
,CMC_CLCL_CLAIM.CLCL_TOT_PAYABLE as 'totalPayable'
,CMC_CLCL_CLAIM.CLCL_PA_PAID_AMT as 'paidAmount'
,CMC_SBSB_SUBSC.SBSB_ID as 'policyNumber'
,LTRIM(RTRIM(CMC_MEME_MEMBER.MEME_LAST_NAME)) + ' ' + LTRIM(RTRIM(CMC_MEME_MEMBER.MEME_MID_INIT)) + ' ' + LTRIM(RTRIM(CMC_MEME_MEMBER.MEME_FIRST_NAME)) AS 'PolicyHolderName'
,CASE 
		WHEN (CMC_MEME_MEMBER.MEME_SEX = 'M') THEN 'Male'
		WHEN (CMC_MEME_MEMBER.MEME_SEX = 'F') THEN 'Female'
		END AS 'Gender'
,CMC_PRPR_PROV.PRPR_NAME as 'providerName'
,CMC_PRPR_PROV.PRPR_NPI as 'npi'
from CMC_CLCL_CLAIM 
INNER JOIN CMC_SBSB_SUBSC ON CMC_SBSB_SUBSC.SBSB_CK = CMC_CLCL_CLAIM.SBSB_CK
INNER JOIN CMC_MEME_MEMBER ON CMC_MEME_MEMBER.MEME_CK = CMC_CLCL_CLAIM.MEME_CK
INNER JOIN CMC_PRPR_PROV ON CMC_PRPR_PROV.PRPR_ID = CMC_CLCL_CLAIM.CLCL_PAYEE_PR_ID
where CMC_CLCL_CLAIM.CLCL_ID = '121300540200'