select CMC_CLCL_CLAIM.CLCL_ID as 'claimId' 
,CASE 
		WHEN (CMC_CLCL_CLAIM.CLCL_CUR_STS = 02) THEN 'Paid'
		WHEN (CMC_CLCL_CLAIM.CLCL_CUR_STS = 01) THEN 'Pending Payment'
		WHEN (CMC_CLCL_CLAIM.CLCL_CUR_STS = 15) THEN 'Pending'
		WHEN (CMC_CLCL_CLAIM.CLCL_CUR_STS = 16) THEN 'Pending'
		ELSE CMC_CLCL_CLAIM.CLCL_CUR_STS			
		END AS 'status'
,CMC_CLCL_CLAIM.CLCL_LOW_SVC_DT	
,CMC_CLCL_CLAIM.CLCL_HIGH_SVC_DT	
from CMC_CLCL_CLAIM 
INNER JOIN CMC_SBSB_SUBSC ON CMC_CLCL_CLAIM.SBSB_CK = CMC_SBSB_SUBSC.SBSB_CK 
where CMC_SBSB_SUBSC.SBSB_ID = 'C00213201'
AND (CMC_CLCL_CLAIM.CLCL_LOW_SVC_DT between '01 January 2012' and '31 December 2012'
		OR CMC_CLCL_CLAIM.CLCL_HIGH_SVC_DT between '01 January 2012' and '31 December 2012')