select distinct CMC_MEPE_PRCS_ELIG.CSPD_CAT AS 'ProductCategoryCode'
,CMC_CSPD_DESC.CSPD_CAT_DESC AS 'ProductCategoryDesc'
from CMC_MEPE_PRCS_ELIG
INNER JOIN CMC_CSPD_DESC ON CMC_CSPD_DESC.CSPD_CAT = CMC_MEPE_PRCS_ELIG.CSPD_CAT