
package com.wellpoint.services.senior.claims.wsdl.claimsinquiry_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClaimsInquiry-v1_0", targetNamespace = "http://services.wellpoint.com/senior/claims/wsdl/ClaimsInquiry-v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsnotes_v2_06.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsresponsibility_v1_0.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimsaccumulator_v2_0.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimsex_v11_01.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimroutingdetails_v2_0.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimshipaaex_v1_10.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsoverridedetail_v1_04.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimssurgicalprocedure_v1_04.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsadjudicationdetail_v2_02.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimspaymentsummary_v3_01.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getmemberclaimdetail_v2_03.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getcoordofbenefitsdata_v1_0.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimseobdetailsex_v2_0.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimspaymentdetail_v2_1.ObjectFactory.class,
    com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimseobdetaillegacy_v1_0.ObjectFactory.class
})
public interface ClaimsInquiryV10 {


    /**
     * 
     * @param getClaimsNotesReq
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsnotes_v2_06.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsNotes-v2_06", partName = "getClaimsNotesRes")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsnotes_v2_06.PayLoad getClaimsNotes(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsNotes-v2_06", partName = "getClaimsNotesReq")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsnotes_v2_06.PayLoad getClaimsNotesReq);

    /**
     * 
     * @param getClaimsResponsibilityReq
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsresponsibility_v1_0.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsResponsibility-v1_0", partName = "getClaimsResponsibilityRes")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsresponsibility_v1_0.PayLoad getClaimsResponsibility(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsResponsibility-v1_0", partName = "getClaimsResponsibilityReq")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsresponsibility_v1_0.PayLoad getClaimsResponsibilityReq);

    /**
     * 
     * @param searchClaimsAccumulatorReq
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimsaccumulator_v2_0.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/searchClaimsAccumulator-v2_0", partName = "searchClaimsAccumulatorRes")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimsaccumulator_v2_0.PayLoad searchClaimsAccumulator(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/searchClaimsAccumulator-v2_0", partName = "searchClaimsAccumulatorReq")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimsaccumulator_v2_0.PayLoad searchClaimsAccumulatorReq);

    /**
     * 
     * @param searchClaimsExReq
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimsex_v11_01.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/searchClaimsEx-v11_01", partName = "searchClaimsExRes")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimsex_v11_01.PayLoad searchClaimsEx(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/searchClaimsEx-v11_01", partName = "searchClaimsExReq")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimsex_v11_01.PayLoad searchClaimsExReq);

    /**
     * 
     * @param getClaimRoutingDetailRequest
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimroutingdetails_v2_0.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimRoutingDetails-v2_0", partName = "getClaimRoutingDetailResponse")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimroutingdetails_v2_0.PayLoad getClaimRoutingDetails(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimRoutingDetails-v2_0", partName = "getClaimRoutingDetailRequest")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimroutingdetails_v2_0.PayLoad getClaimRoutingDetailRequest);

    /**
     * 
     * @param getClaimsHIPAAExRequest
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimshipaaex_v1_10.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsHipaaEx-v1_10", partName = "getClaimsHIPAAExResponse")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimshipaaex_v1_10.PayLoad getClaimsHipaaEx(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsHipaaEx-v1_10", partName = "getClaimsHIPAAExRequest")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimshipaaex_v1_10.PayLoad getClaimsHIPAAExRequest);

    /**
     * 
     * @param getClaimsOverrideDetailRequest
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsoverridedetail_v1_04.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsOverrideDetail-v1_04", partName = "getClaimsOverrideDetailResponse")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsoverridedetail_v1_04.PayLoad getClaimsOverrideDetail(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsOverrideDetail-v1_04", partName = "getClaimsOverrideDetailRequest")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsoverridedetail_v1_04.PayLoad getClaimsOverrideDetailRequest);

    /**
     * 
     * @param getClaimsSurgicalProcedureRequest
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimssurgicalprocedure_v1_04.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsSurgicalProcedure-v1_04", partName = "getClaimsSurgicalProcedureResponse")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimssurgicalprocedure_v1_04.PayLoad getClaimsSurgicalProcedure(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsSurgicalProcedure-v1_04", partName = "getClaimsSurgicalProcedureRequest")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimssurgicalprocedure_v1_04.PayLoad getClaimsSurgicalProcedureRequest);

    /**
     * 
     * @param getClaimsEOBDetailLegacyRequest
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimseobdetaillegacy_v1_0.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/SearchClaimsEOBDetailLegacy-v1_0", partName = "getClaimsEOBDetailLegacyResponse")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimseobdetaillegacy_v1_0.PayLoad getClaimsEOBDetailLegacy(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/SearchClaimsEOBDetailLegacy-v1_0", partName = "getClaimsEOBDetailLegacyRequest")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.searchclaimseobdetaillegacy_v1_0.PayLoad getClaimsEOBDetailLegacyRequest);

    /**
     * 
     * @param getClaimsPaymentSummaryExRequest
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimspaymentsummary_v3_01.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsPaymentSummary-v3_01", partName = "getClaimsPaymentSummaryExResponse")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimspaymentsummary_v3_01.PayLoad getClaimsPaymentSummaryEx(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getClaimsPaymentSummary-v3_01", partName = "getClaimsPaymentSummaryExRequest")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimspaymentsummary_v3_01.PayLoad getClaimsPaymentSummaryExRequest);

    /**
     * 
     * @param getClmsAdjdctnDtlRqst
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsadjudicationdetail_v2_02.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/GetClaimsAdjudicationDetail-v2_02", partName = "GetClmsAdjdctnDtlResp")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsadjudicationdetail_v2_02.PayLoad getClaimsAdjudicationDetails(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/GetClaimsAdjudicationDetail-v2_02", partName = "GetClmsAdjdctnDtlRqst")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimsadjudicationdetail_v2_02.PayLoad getClmsAdjdctnDtlRqst);

    /**
     * 
     * @param getCoordOfBenefitsDataRequest
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getcoordofbenefitsdata_v1_0.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getCoordOfBenefitsData-v1_0", partName = "GetCoordOfBenefitsDataResponse")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getcoordofbenefitsdata_v1_0.PayLoad getCoordOfBenefitsData(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getCoordOfBenefitsData-v1_0", partName = "GetCoordOfBenefitsDataRequest")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getcoordofbenefitsdata_v1_0.PayLoad getCoordOfBenefitsDataRequest);

    /**
     * 
     * @param getMemberClaimsDetailRequest
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getmemberclaimdetail_v2_03.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getMemberClaimDetail-v2_03", partName = "GetMemberClaimsDetailResponse")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getmemberclaimdetail_v2_03.PayLoad getMemberClaimDetail(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/getMemberClaimDetail-v2_03", partName = "GetMemberClaimsDetailRequest")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getmemberclaimdetail_v2_03.PayLoad getMemberClaimsDetailRequest);

    /**
     * 
     * @param getClaimsPaymentDetailExRequestV1
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimspaymentdetail_v2_1.PayLoad
     */
    @WebMethod(operationName = "getClaimsPaymentDetail_Ex")
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/GetClaimsPaymentDetail-v2_1", partName = "getClaimsPaymentDetailExResponse_V1")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimspaymentdetail_v2_1.PayLoad getClaimsPaymentDetailEx(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/GetClaimsPaymentDetail-v2_1", partName = "getClaimsPaymentDetailExRequest_V1")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimspaymentdetail_v2_1.PayLoad getClaimsPaymentDetailExRequestV1);

    /**
     * 
     * @param getClaimsEOBDetailExRequest
     * @return
     *     returns com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimseobdetailsex_v2_0.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/GetClaimsEOBDetailsEx-v2_0", partName = "getClaimsEOBDetailExResponse")
    public com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimseobdetailsex_v2_0.PayLoad getClaimsEOBDetailEx(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/claims/schemas/ClaimsInquiry/GetClaimsEOBDetailsEx-v2_0", partName = "getClaimsEOBDetailExRequest")
        com.wellpoint.services.senior.claims.schemas.claimsinquiry.getclaimseobdetailsex_v2_0.PayLoad getClaimsEOBDetailExRequest);

}
