
package com.wellpoint.services.senior.claims.wsdl.claimsinquiry_v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClaimsInquiry-v1_0", targetNamespace = "http://services.wellpoint.com/senior/claims/wsdl/ClaimsInquiry-v1", wsdlLocation = "file:/D:/CareMore%20TFS%20Check/Local%20Tries/wsdl/claims/ClaimsInquiry-v1.wsdl")
public class ClaimsInquiryV10_Service
    extends Service
{

    private final static URL CLAIMSINQUIRYV10_WSDL_LOCATION;
    private final static WebServiceException CLAIMSINQUIRYV10_EXCEPTION;
    private final static QName CLAIMSINQUIRYV10_QNAME = new QName("http://services.wellpoint.com/senior/claims/wsdl/ClaimsInquiry-v1", "ClaimsInquiry-v1_0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/CareMore%20TFS%20Check/Local%20Tries/wsdl/claims/ClaimsInquiry-v1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLAIMSINQUIRYV10_WSDL_LOCATION = url;
        CLAIMSINQUIRYV10_EXCEPTION = e;
    }

    public ClaimsInquiryV10_Service() {
        super(__getWsdlLocation(), CLAIMSINQUIRYV10_QNAME);
    }

    public ClaimsInquiryV10_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLAIMSINQUIRYV10_QNAME, features);
    }

    public ClaimsInquiryV10_Service(URL wsdlLocation) {
        super(wsdlLocation, CLAIMSINQUIRYV10_QNAME);
    }

    public ClaimsInquiryV10_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLAIMSINQUIRYV10_QNAME, features);
    }

    public ClaimsInquiryV10_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClaimsInquiryV10_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClaimsInquiryV10
     */
    @WebEndpoint(name = "ClaimsInquiryImpl")
    public ClaimsInquiryV10 getClaimsInquiryImpl() {
        return super.getPort(new QName("http://services.wellpoint.com/senior/claims/wsdl/ClaimsInquiry-v1", "ClaimsInquiryImpl"), ClaimsInquiryV10.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClaimsInquiryV10
     */
    @WebEndpoint(name = "ClaimsInquiryImpl")
    public ClaimsInquiryV10 getClaimsInquiryImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.wellpoint.com/senior/claims/wsdl/ClaimsInquiry-v1", "ClaimsInquiryImpl"), ClaimsInquiryV10.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLAIMSINQUIRYV10_EXCEPTION!= null) {
            throw CLAIMSINQUIRYV10_EXCEPTION;
        }
        return CLAIMSINQUIRYV10_WSDL_LOCATION;
    }

}
