
package com.wellpoint.services.senior.member.wsdl.membermanagement_v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MemberManagement-v1_0", targetNamespace = "http://services.wellpoint.com/senior/member/wsdl/MemberManagement-v1", wsdlLocation = "file:/D:/CareMore%20TFS%20Check/Local%20Tries/wsdl/member/MemberManagement-v1.wsdl")
public class MemberManagementV10_Service
    extends Service
{

    private final static URL MEMBERMANAGEMENTV10_WSDL_LOCATION;
    private final static WebServiceException MEMBERMANAGEMENTV10_EXCEPTION;
    private final static QName MEMBERMANAGEMENTV10_QNAME = new QName("http://services.wellpoint.com/senior/member/wsdl/MemberManagement-v1", "MemberManagement-v1_0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/CareMore%20TFS%20Check/Local%20Tries/wsdl/member/MemberManagement-v1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEMBERMANAGEMENTV10_WSDL_LOCATION = url;
        MEMBERMANAGEMENTV10_EXCEPTION = e;
    }

    public MemberManagementV10_Service() {
        super(__getWsdlLocation(), MEMBERMANAGEMENTV10_QNAME);
    }

    public MemberManagementV10_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEMBERMANAGEMENTV10_QNAME, features);
    }

    public MemberManagementV10_Service(URL wsdlLocation) {
        super(wsdlLocation, MEMBERMANAGEMENTV10_QNAME);
    }

    public MemberManagementV10_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEMBERMANAGEMENTV10_QNAME, features);
    }

    public MemberManagementV10_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberManagementV10_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MemberManagementV10
     */
    @WebEndpoint(name = "MemberManagementImpl")
    public MemberManagementV10 getMemberManagementImpl() {
        return super.getPort(new QName("http://services.wellpoint.com/senior/member/wsdl/MemberManagement-v1", "MemberManagementImpl"), MemberManagementV10.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberManagementV10
     */
    @WebEndpoint(name = "MemberManagementImpl")
    public MemberManagementV10 getMemberManagementImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.wellpoint.com/senior/member/wsdl/MemberManagement-v1", "MemberManagementImpl"), MemberManagementV10.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEMBERMANAGEMENTV10_EXCEPTION!= null) {
            throw MEMBERMANAGEMENTV10_EXCEPTION;
        }
        return MEMBERMANAGEMENTV10_WSDL_LOCATION;
    }

}
