
package com.wellpoint.services.senior.provider.wsdl.providerclaimsinquiry_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.wellpoint.services.senior.provider.schemas.providerclaimsinquiry.searchproviderclaims_v200.ObjectFactory;
import com.wellpoint.services.senior.provider.schemas.providerclaimsinquiry.searchproviderclaims_v200.PayLoad;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProviderClaimsInquiry-v1_0", targetNamespace = "http://services.wellpoint.com/senior/provider/wsdl/ProviderClaimsInquiry-v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProviderClaimsInquiryV10 {


    /**
     * 
     * @param searchProviderClaimsRequest
     * @return
     *     returns com.wellpoint.services.senior.provider.schemas.providerclaimsinquiry.searchproviderclaims_v200.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/provider/schemas/ProviderClaimsInquiry/searchProviderClaims-v200", partName = "searchProviderClaimsResponse")
    public PayLoad searchProviderClaims(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/provider/schemas/ProviderClaimsInquiry/searchProviderClaims-v200", partName = "searchProviderClaimsRequest")
        PayLoad searchProviderClaimsRequest);

}
