
package com.wellpoint.services.senior.provider.wsdl.providerclaimsinquiry_v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProviderClaimsInquiry-v1_0", targetNamespace = "http://services.wellpoint.com/senior/provider/wsdl/ProviderClaimsInquiry-v1", wsdlLocation = "file:/D:/CareMore%20TFS%20Check/Local%20Tries/wsdl/provider/ProviderClaimsInquiry-v1.wsdl")
public class ProviderClaimsInquiryV10_Service
    extends Service
{

    private final static URL PROVIDERCLAIMSINQUIRYV10_WSDL_LOCATION;
    private final static WebServiceException PROVIDERCLAIMSINQUIRYV10_EXCEPTION;
    private final static QName PROVIDERCLAIMSINQUIRYV10_QNAME = new QName("http://services.wellpoint.com/senior/provider/wsdl/ProviderClaimsInquiry-v1", "ProviderClaimsInquiry-v1_0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/CareMore%20TFS%20Check/Local%20Tries/wsdl/provider/ProviderClaimsInquiry-v1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROVIDERCLAIMSINQUIRYV10_WSDL_LOCATION = url;
        PROVIDERCLAIMSINQUIRYV10_EXCEPTION = e;
    }

    public ProviderClaimsInquiryV10_Service() {
        super(__getWsdlLocation(), PROVIDERCLAIMSINQUIRYV10_QNAME);
    }

    public ProviderClaimsInquiryV10_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVIDERCLAIMSINQUIRYV10_QNAME, features);
    }

    public ProviderClaimsInquiryV10_Service(URL wsdlLocation) {
        super(wsdlLocation, PROVIDERCLAIMSINQUIRYV10_QNAME);
    }

    public ProviderClaimsInquiryV10_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVIDERCLAIMSINQUIRYV10_QNAME, features);
    }

    public ProviderClaimsInquiryV10_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProviderClaimsInquiryV10_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProviderClaimsInquiryV10
     */
    @WebEndpoint(name = "ProviderClaimsInquiry-v1_0Impl")
    public ProviderClaimsInquiryV10 getProviderClaimsInquiryV10Impl() {
        return super.getPort(new QName("http://services.wellpoint.com/senior/provider/wsdl/ProviderClaimsInquiry-v1", "ProviderClaimsInquiry-v1_0Impl"), ProviderClaimsInquiryV10.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProviderClaimsInquiryV10
     */
    @WebEndpoint(name = "ProviderClaimsInquiry-v1_0Impl")
    public ProviderClaimsInquiryV10 getProviderClaimsInquiryV10Impl(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.wellpoint.com/senior/provider/wsdl/ProviderClaimsInquiry-v1", "ProviderClaimsInquiry-v1_0Impl"), ProviderClaimsInquiryV10.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVIDERCLAIMSINQUIRYV10_EXCEPTION!= null) {
            throw PROVIDERCLAIMSINQUIRYV10_EXCEPTION;
        }
        return PROVIDERCLAIMSINQUIRYV10_WSDL_LOCATION;
    }

}
