
package com.wellpoint.services.senior.product.wsdl.benefitsinquiry_v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BenefitsInquiry-v1_0", targetNamespace = "http://services.wellpoint.com/senior/product/wsdl/BenefitsInquiry-v1", wsdlLocation = "file:/D:/CareMore%20TFS%20Check/Local%20Tries/wsdl/product/BenefitsInquiry-v1.wsdl")
public class BenefitsInquiryV10_Service
    extends Service
{

    private final static URL BENEFITSINQUIRYV10_WSDL_LOCATION;
    private final static WebServiceException BENEFITSINQUIRYV10_EXCEPTION;
    private final static QName BENEFITSINQUIRYV10_QNAME = new QName("http://services.wellpoint.com/senior/product/wsdl/BenefitsInquiry-v1", "BenefitsInquiry-v1_0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/CareMore%20TFS%20Check/Local%20Tries/wsdl/product/BenefitsInquiry-v1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BENEFITSINQUIRYV10_WSDL_LOCATION = url;
        BENEFITSINQUIRYV10_EXCEPTION = e;
    }

    public BenefitsInquiryV10_Service() {
        super(__getWsdlLocation(), BENEFITSINQUIRYV10_QNAME);
    }

    public BenefitsInquiryV10_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BENEFITSINQUIRYV10_QNAME, features);
    }

    public BenefitsInquiryV10_Service(URL wsdlLocation) {
        super(wsdlLocation, BENEFITSINQUIRYV10_QNAME);
    }

    public BenefitsInquiryV10_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BENEFITSINQUIRYV10_QNAME, features);
    }

    public BenefitsInquiryV10_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BenefitsInquiryV10_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BenefitsInquiryV10
     */
    @WebEndpoint(name = "BenefitsInquiryv1_0Impl")
    public BenefitsInquiryV10 getBenefitsInquiryv10Impl() {
        return super.getPort(new QName("http://services.wellpoint.com/senior/product/wsdl/BenefitsInquiry-v1", "BenefitsInquiryv1_0Impl"), BenefitsInquiryV10.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BenefitsInquiryV10
     */
    @WebEndpoint(name = "BenefitsInquiryv1_0Impl")
    public BenefitsInquiryV10 getBenefitsInquiryv10Impl(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.wellpoint.com/senior/product/wsdl/BenefitsInquiry-v1", "BenefitsInquiryv1_0Impl"), BenefitsInquiryV10.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BENEFITSINQUIRYV10_EXCEPTION!= null) {
            throw BENEFITSINQUIRYV10_EXCEPTION;
        }
        return BENEFITSINQUIRYV10_WSDL_LOCATION;
    }

}
