
package com.wellpoint.services.senior.product.wsdl.benefitsinquiry_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BenefitsInquiry-v1_0", targetNamespace = "http://services.wellpoint.com/senior/product/wsdl/BenefitsInquiry-v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.wellpoint.services.senior.product.schemas.benefitsinquiry.searchbenefitsnotes_v1_0.ObjectFactory.class,
    com.wellpoint.services.senior.product.schemas.benefitsinquiry.get27xbenefitaccums_v3_0.ObjectFactory.class
})
public interface BenefitsInquiryV10 {


    /**
     * 
     * @param searchBenefitsNotesRequest
     * @return
     *     returns com.wellpoint.services.senior.product.schemas.benefitsinquiry.searchbenefitsnotes_v1_0.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/product/schemas/BenefitsInquiry/searchBenefitsNotes-v1_0", partName = "searchBenefitsNotesResponse")
    public com.wellpoint.services.senior.product.schemas.benefitsinquiry.searchbenefitsnotes_v1_0.PayLoad searchBenefitsNotes(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/product/schemas/BenefitsInquiry/searchBenefitsNotes-v1_0", partName = "searchBenefitsNotesRequest")
        com.wellpoint.services.senior.product.schemas.benefitsinquiry.searchbenefitsnotes_v1_0.PayLoad searchBenefitsNotesRequest);

    /**
     * 
     * @param get27XBenefitAccumsRequest
     * @return
     *     returns com.wellpoint.services.senior.product.schemas.benefitsinquiry.get27xbenefitaccums_v3_0.PayLoad
     */
    @WebMethod
    @WebResult(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/product/schemas/BenefitsInquiry/get27XBenefitAccums-v3_0", partName = "get27XBenefitAccumsResponse")
    public com.wellpoint.services.senior.product.schemas.benefitsinquiry.get27xbenefitaccums_v3_0.PayLoad get27XBenefitAccums(
        @WebParam(name = "PayLoad", targetNamespace = "http://services.wellpoint.com/senior/product/schemas/BenefitsInquiry/get27XBenefitAccums-v3_0", partName = "get27XBenefitAccumsRequest")
        com.wellpoint.services.senior.product.schemas.benefitsinquiry.get27xbenefitaccums_v3_0.PayLoad get27XBenefitAccumsRequest);

}
