package com.cybermint.serpScraper.hibernate;
// Generated May 28, 2011 5:31:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Keywords generated by hbm2java
 */
public class Keywords  implements java.io.Serializable {


     private Long keywordId;
     private Projects projects;
     private String keyword;
     private String status;
     private Long seobc;
     private Long seopc;
     private Long seotc;
     private Long seobli;
     private Long seopli;
     private Set urlses = new HashSet(0);

    public Keywords() {
    }

	
    public Keywords(Projects projects, String keyword, String status) {
        this.projects = projects;
        this.keyword = keyword;
        this.status = status;
    }
    public Keywords(Projects projects, String keyword, String status, Long seobc, Long seopc, Long seotc, Long seobli, Long seopli, Set urlses) {
       this.projects = projects;
       this.keyword = keyword;
       this.status = status;
       this.seobc = seobc;
       this.seopc = seopc;
       this.seotc = seotc;
       this.seobli = seobli;
       this.seopli = seopli;
       this.urlses = urlses;
    }
   
    public Long getKeywordId() {
        return this.keywordId;
    }
    
    public void setKeywordId(Long keywordId) {
        this.keywordId = keywordId;
    }
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }
    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Long getSeobc() {
        return this.seobc;
    }
    
    public void setSeobc(Long seobc) {
        this.seobc = seobc;
    }
    public Long getSeopc() {
        return this.seopc;
    }
    
    public void setSeopc(Long seopc) {
        this.seopc = seopc;
    }
    public Long getSeotc() {
        return this.seotc;
    }
    
    public void setSeotc(Long seotc) {
        this.seotc = seotc;
    }
    public Long getSeobli() {
        return this.seobli;
    }
    
    public void setSeobli(Long seobli) {
        this.seobli = seobli;
    }
    public Long getSeopli() {
        return this.seopli;
    }
    
    public void setSeopli(Long seopli) {
        this.seopli = seopli;
    }
    public Set getUrlses() {
        return this.urlses;
    }
    
    public void setUrlses(Set urlses) {
        this.urlses = urlses;
    }




}


