package com.cybermint.serpScraper.domains;
// Generated Nov 25, 2010 3:41:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Keyword generated by hbm2java
 */
public class Keyword  implements java.io.Serializable {


     private BigDecimal keywordId;
     private Project project;
     private String keyword;
     private String status;
     private Set<Url> urls = new HashSet<Url>(0);
     private BigDecimal SEOBC;
     private BigDecimal SEOPC;
     private BigDecimal SEOTC;
     private BigDecimal SEOBLI;
     private BigDecimal SEOPLI;

    public Keyword() {
    }

    public Keyword(Project project, String keyword,String status) {
        this.project = project;
        this.keyword = keyword;
        this.status = status;
    }

	
    public Keyword(Project project, BigDecimal keywordId, String keyword, String status) {
        this.project = project;
        this.keywordId = keywordId;
        this.keyword = keyword;
        this.status = status;
    }
    public Keyword(Project project, BigDecimal keywordId, String keyword, String status, Set<Url> urls, BigDecimal SEOBC, BigDecimal SEOPC,
            BigDecimal SEOTC, BigDecimal SEOBLI, BigDecimal SEOPLI) {
       this.project = project;
       this.keywordId = keywordId;
       this.keyword = keyword;
       this.status = status;
       this.urls = urls;
       this.SEOBC = SEOBC;
       this.SEOPC = SEOPC;
       this.SEOTC = SEOTC;
       this.SEOBLI = SEOBLI;
       this.SEOPLI = SEOPLI;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public BigDecimal getKeywordId() {
        return this.keywordId;
    }
    
    public void setKeywordId(BigDecimal keywordId) {
        this.keywordId = keywordId;
    }
    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Url> getUrls() {
        return this.urls;
    }
    
    public void setUrls(Set<Url> urls) {
        this.urls = urls;
    }

    public BigDecimal getSEOBC() {
        return SEOBC;
    }

    public void setSEOBC(BigDecimal SEOBC) {
        this.SEOBC = SEOBC;
    }

    public BigDecimal getSEOBLI() {
        return SEOBLI;
    }

    public void setSEOBLI(BigDecimal SEOBLI) {
        this.SEOBLI = SEOBLI;
    }

    public BigDecimal getSEOPC() {
        return SEOPC;
    }

    public void setSEOPC(BigDecimal SEOPC) {
        this.SEOPC = SEOPC;
    }

    public BigDecimal getSEOPLI() {
        return SEOPLI;
    }

    public void setSEOPLI(BigDecimal SEOPLI) {
        this.SEOPLI = SEOPLI;
    }

    public BigDecimal getSEOTC() {
        return SEOTC;
    }

    public void setSEOTC(BigDecimal SEOTC) {
        this.SEOTC = SEOTC;
    }


}


