package com.cybermint.serpScraper.domains;
// Generated May 28, 2011 5:31:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private Integer projectId;
     private String projectName;
     private String projectDesc;
     private Set keywords = new HashSet(0);
     private Set urls = new HashSet(0);

    public Project() {
    }

	
    public Project(String projectName) {
        this.projectName = projectName;
    }

    public Project(String projectName, String projectDesc) {
        this.projectName = projectName;
        this.projectDesc = projectDesc;
    }
    
    public Project(String projectName, String projectDesc, Set keywords, Set urls) {
       this.projectName = projectName;
       this.projectDesc = projectDesc;
       this.keywords = keywords;
       this.urls = urls;
    }
   
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public String getProjectDesc() {
        return this.projectDesc;
    }
    
    public void setProjectDesc(String projectDesc) {
        this.projectDesc = projectDesc;
    }
    public Set getKeywords() {
        return this.keywords;
    }
    
    public void setKeywords(Set keywords) {
        this.keywords = keywords;
    }
    public Set getUrls() {
        return this.urls;
    }
    
    public void setUrls(Set urls) {
        this.urls = urls;
    }

}