package com.cybermint.serpScraper.domains;
// Generated Nov 25, 2010 3:41:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.net.URL;

/**
 * Url generated by hbm2java
 */
public class Url  implements java.io.Serializable {


     private BigDecimal urlId;
     private Keyword keyword;
     private Project project;
     private String url;
     private String domain;
     private String resultType;
     private BigDecimal rank;
     private String majesticSeoBacklinksStatus;
 	 private String majesticSeoUrlType;
 	 private BigDecimal majesticSeoACRank;
 	 private BigDecimal majesticSeoExternalBacklinksCount;
 	 private BigDecimal majesticSeoGovExternalBacklinksCount;
 	 private BigDecimal majesticSeoEduExternalBacklinksCount;
 	 private BigDecimal majesticSeoReferringDomainsCount;
 	 private BigDecimal majesticSeoGovReferringDomainsCount;
 	 private BigDecimal majesticSeoEduReferringDomainsCount;
 	 private BigDecimal majesticSeoIPAddressesCount;
 	 private BigDecimal majesticSeoClassCSubnetsCount;
 	 private String majesticSeoBacklinksToDomainStatus;
 	 private BigDecimal majesticSeoExternalBacklinksToDomainCount;
	 private BigDecimal majesticSeoGovExternalBacklinksToDomainCount;
	 private BigDecimal majesticSeoEduExternalBacklinksToDomainCount;
	 private BigDecimal majesticSeoReferringDomainsToDomainCount;
	 private BigDecimal majesticSeoGovReferringDomainsToDomainCount;
	 private BigDecimal majesticSeoEduReferringDomainsToDomainCount;
	 private BigDecimal majesticSeoIPAddressesToDomainCount;
	 private BigDecimal majesticSeoClassCSubnetsToDomainCount;

    public Url() {
    }

	
    public Url(Project project, BigDecimal urlId, String domain, String url) {
        this.project = project;
        this.urlId = urlId;
        this.url = url;
        this.domain = domain;
    }
    public Url(BigDecimal urlId, Keyword keyword, Project project, String domain, String url, BigDecimal rank) {
       this.urlId = urlId;
       this.keyword = keyword;
       this.project = project;
       this.url = url;
       this.rank = rank;
       this.domain = domain;
    }
   
    /**
	 * @param urlId
	 * @param keyword
	 * @param project
	 * @param url
	 * @param domain
	 * @param rank
	 * @param majesticSeoBacklinksStatus
	 * @param majesticSeoUrlType
	 * @param majesticSeoACRank
	 * @param majesticSeoExternalBacklinksCount
	 * @param majesticSeoGovExternalBacklinksCount
	 * @param majesticSeoEduExternalBacklinksCount
	 * @param majesticSeoReferringDomainsCount
	 * @param majesticSeoGovReferringDomainsCount
	 * @param majesticSeoEduReferringDomainsCount
	 * @param majesticSeoIPAddressesCount
	 * @param majesticSeoClassCSubnetsCount
	 */
	public Url(BigDecimal urlId, Keyword keyword, Project project, String url,
			String domain, BigDecimal rank, String majesticSeoBacklinksStatus,
			String majesticSeoUrlType, BigDecimal majesticSeoACRank,
			BigDecimal majesticSeoExternalBacklinksCount,
			BigDecimal majesticSeoGovExternalBacklinksCount,
			BigDecimal majesticSeoEduExternalBacklinksCount,
			BigDecimal majesticSeoReferringDomainsCount,
			BigDecimal majesticSeoGovReferringDomainsCount,
			BigDecimal majesticSeoEduReferringDomainsCount,
			BigDecimal majesticSeoIPAddressesCount,
			BigDecimal majesticSeoClassCSubnetsCount) {
		super();
		this.urlId = urlId;
		this.keyword = keyword;
		this.project = project;
		this.url = url;
		this.domain = domain;
		this.rank = rank;
		this.majesticSeoBacklinksStatus = majesticSeoBacklinksStatus;
		this.majesticSeoUrlType = majesticSeoUrlType;
		this.majesticSeoACRank = majesticSeoACRank;
		this.majesticSeoExternalBacklinksCount = majesticSeoExternalBacklinksCount;
		this.majesticSeoGovExternalBacklinksCount = majesticSeoGovExternalBacklinksCount;
		this.majesticSeoEduExternalBacklinksCount = majesticSeoEduExternalBacklinksCount;
		this.majesticSeoReferringDomainsCount = majesticSeoReferringDomainsCount;
		this.majesticSeoGovReferringDomainsCount = majesticSeoGovReferringDomainsCount;
		this.majesticSeoEduReferringDomainsCount = majesticSeoEduReferringDomainsCount;
		this.majesticSeoIPAddressesCount = majesticSeoIPAddressesCount;
		this.majesticSeoClassCSubnetsCount = majesticSeoClassCSubnetsCount;
	}


	public BigDecimal getUrlId() {
        return this.urlId;
    }
    
    public void setUrlId(BigDecimal urlId) {
        this.urlId = urlId;
    }
    public Keyword getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(Keyword keyword) {
        this.keyword = keyword;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public BigDecimal getRank() {
        return this.rank;
    }
    
    public void setRank(BigDecimal rank) {
        this.rank = rank;
    }


	/**
	 * @return the majesticSeoBacklinksStatus
	 */
	public String getMajesticSeoBacklinksStatus() {
		return majesticSeoBacklinksStatus;
	}


	/**
	 * @param majesticSeoBacklinksStatus the majesticSeoBacklinksStatus to set
	 */
	public void setMajesticSeoBacklinksStatus(String majesticSeoBacklinksStatus) {
		this.majesticSeoBacklinksStatus = majesticSeoBacklinksStatus;
	}


	/**
	 * @return the majesticSeoUrlType
	 */
	public String getMajesticSeoUrlType() {
		return majesticSeoUrlType;
	}


	/**
	 * @param majesticSeoUrlType the majesticSeoUrlType to set
	 */
	public void setMajesticSeoUrlType(String majesticSeoUrlType) {
		this.majesticSeoUrlType = majesticSeoUrlType;
	}


	/**
	 * @return the majesticSeoACRank
	 */
	public BigDecimal getMajesticSeoACRank() {
		return majesticSeoACRank;
	}


	/**
	 * @param majesticSeoACRank the majesticSeoACRank to set
	 */
	public void setMajesticSeoACRank(BigDecimal majesticSeoACRank) {
		this.majesticSeoACRank = majesticSeoACRank;
	}


	/**
	 * @return the majesticSeoExternalBacklinksCount
	 */
	public BigDecimal getMajesticSeoExternalBacklinksCount() {
		return majesticSeoExternalBacklinksCount;
	}


	/**
	 * @param majesticSeoExternalBacklinksCount the majesticSeoExternalBacklinksCount to set
	 */
	public void setMajesticSeoExternalBacklinksCount(
			BigDecimal majesticSeoExternalBacklinksCount) {
		this.majesticSeoExternalBacklinksCount = majesticSeoExternalBacklinksCount;
	}


	/**
	 * @return the majesticSeoGovExternalBacklinksCount
	 */
	public BigDecimal getMajesticSeoGovExternalBacklinksCount() {
		return majesticSeoGovExternalBacklinksCount;
	}


	/**
	 * @param majesticSeoGovExternalBacklinksCount the majesticSeoGovExternalBacklinksCount to set
	 */
	public void setMajesticSeoGovExternalBacklinksCount(
			BigDecimal majesticSeoGovExternalBacklinksCount) {
		this.majesticSeoGovExternalBacklinksCount = majesticSeoGovExternalBacklinksCount;
	}


	/**
	 * @return the majesticSeoEduExternalBacklinksCount
	 */
	public BigDecimal getMajesticSeoEduExternalBacklinksCount() {
		return majesticSeoEduExternalBacklinksCount;
	}


	/**
	 * @param majesticSeoEduExternalBacklinksCount the majesticSeoEduExternalBacklinksCount to set
	 */
	public void setMajesticSeoEduExternalBacklinksCount(
			BigDecimal majesticSeoEduExternalBacklinksCount) {
		this.majesticSeoEduExternalBacklinksCount = majesticSeoEduExternalBacklinksCount;
	}


	/**
	 * @return the majesticSeoReferringDomainsCount
	 */
	public BigDecimal getMajesticSeoReferringDomainsCount() {
		return majesticSeoReferringDomainsCount;
	}


	/**
	 * @param majesticSeoReferringDomainsCount the majesticSeoReferringDomainsCount to set
	 */
	public void setMajesticSeoReferringDomainsCount(
			BigDecimal majesticSeoReferringDomainsCount) {
		this.majesticSeoReferringDomainsCount = majesticSeoReferringDomainsCount;
	}


	/**
	 * @return the majesticSeoGovReferringDomainsCount
	 */
	public BigDecimal getMajesticSeoGovReferringDomainsCount() {
		return majesticSeoGovReferringDomainsCount;
	}


	/**
	 * @param majesticSeoGovReferringDomainsCount the majesticSeoGovReferringDomainsCount to set
	 */
	public void setMajesticSeoGovReferringDomainsCount(
			BigDecimal majesticSeoGovReferringDomainsCount) {
		this.majesticSeoGovReferringDomainsCount = majesticSeoGovReferringDomainsCount;
	}


	/**
	 * @return the majesticSeoEduReferringDomainsCount
	 */
	public BigDecimal getMajesticSeoEduReferringDomainsCount() {
		return majesticSeoEduReferringDomainsCount;
	}


	/**
	 * @param majesticSeoEduReferringDomainsCount the majesticSeoEduReferringDomainsCount to set
	 */
	public void setMajesticSeoEduReferringDomainsCount(
			BigDecimal majesticSeoEduReferringDomainsCount) {
		this.majesticSeoEduReferringDomainsCount = majesticSeoEduReferringDomainsCount;
	}


	/**
	 * @return the majesticSeoIPAddressesCount
	 */
	public BigDecimal getMajesticSeoIPAddressesCount() {
		return majesticSeoIPAddressesCount;
	}


	/**
	 * @param majesticSeoIPAddressesCount the majesticSeoIPAddressesCount to set
	 */
	public void setMajesticSeoIPAddressesCount(
			BigDecimal majesticSeoIPAddressesCount) {
		this.majesticSeoIPAddressesCount = majesticSeoIPAddressesCount;
	}


	/**
	 * @return the majesticSeoClassCSubnetsCount
	 */
	public BigDecimal getMajesticSeoClassCSubnetsCount() {
		return majesticSeoClassCSubnetsCount;
	}


	/**
	 * @param majesticSeoClassCSubnetsCount the majesticSeoClassCSubnetsCount to set
	 */
	public void setMajesticSeoClassCSubnetsCount(
			BigDecimal majesticSeoClassCSubnetsCount) {
		this.majesticSeoClassCSubnetsCount = majesticSeoClassCSubnetsCount;
	}


	/**
	 * @return the majesticSeoBacklinksToDomainStatus
	 */
	public String getMajesticSeoBacklinksToDomainStatus() {
		return majesticSeoBacklinksToDomainStatus;
	}


	/**
	 * @param majesticSeoBacklinksToDomainStatus the majesticSeoBacklinksToDomainStatus to set
	 */
	public void setMajesticSeoBacklinksToDomainStatus(
			String majesticSeoBacklinksToDomainStatus) {
		this.majesticSeoBacklinksToDomainStatus = majesticSeoBacklinksToDomainStatus;
	}


	/**
	 * @return the majesticSeoExternalBacklinksToDomainCount
	 */
	public BigDecimal getMajesticSeoExternalBacklinksToDomainCount() {
		return majesticSeoExternalBacklinksToDomainCount;
	}


	/**
	 * @param majesticSeoExternalBacklinksToDomainCount the majesticSeoExternalBacklinksToDomainCount to set
	 */
	public void setMajesticSeoExternalBacklinksToDomainCount(
			BigDecimal majesticSeoExternalBacklinksToDomainCount) {
		this.majesticSeoExternalBacklinksToDomainCount = majesticSeoExternalBacklinksToDomainCount;
	}


	/**
	 * @return the majesticSeoGovExternalBacklinksToDomainCount
	 */
	public BigDecimal getMajesticSeoGovExternalBacklinksToDomainCount() {
		return majesticSeoGovExternalBacklinksToDomainCount;
	}


	/**
	 * @param majesticSeoGovExternalBacklinksToDomainCount the majesticSeoGovExternalBacklinksToDomainCount to set
	 */
	public void setMajesticSeoGovExternalBacklinksToDomainCount(
			BigDecimal majesticSeoGovExternalBacklinksToDomainCount) {
		this.majesticSeoGovExternalBacklinksToDomainCount = majesticSeoGovExternalBacklinksToDomainCount;
	}


	/**
	 * @return the majesticSeoEduExternalBacklinksToDomainCount
	 */
	public BigDecimal getMajesticSeoEduExternalBacklinksToDomainCount() {
		return majesticSeoEduExternalBacklinksToDomainCount;
	}


	/**
	 * @param majesticSeoEduExternalBacklinksToDomainCount the majesticSeoEduExternalBacklinksToDomainCount to set
	 */
	public void setMajesticSeoEduExternalBacklinksToDomainCount(
			BigDecimal majesticSeoEduExternalBacklinksToDomainCount) {
		this.majesticSeoEduExternalBacklinksToDomainCount = majesticSeoEduExternalBacklinksToDomainCount;
	}


	/**
	 * @return the majesticSeoReferringDomainsToDomainCount
	 */
	public BigDecimal getMajesticSeoReferringDomainsToDomainCount() {
		return majesticSeoReferringDomainsToDomainCount;
	}


	/**
	 * @param majesticSeoReferringDomainsToDomainCount the majesticSeoReferringDomainsToDomainCount to set
	 */
	public void setMajesticSeoReferringDomainsToDomainCount(
			BigDecimal majesticSeoReferringDomainsToDomainCount) {
		this.majesticSeoReferringDomainsToDomainCount = majesticSeoReferringDomainsToDomainCount;
	}


	/**
	 * @return the majesticSeoGovReferringDomainsToDomainCount
	 */
	public BigDecimal getMajesticSeoGovReferringDomainsToDomainCount() {
		return majesticSeoGovReferringDomainsToDomainCount;
	}


	/**
	 * @param majesticSeoGovReferringDomainsToDomainCount the majesticSeoGovReferringDomainsToDomainCount to set
	 */
	public void setMajesticSeoGovReferringDomainsToDomainCount(
			BigDecimal majesticSeoGovReferringDomainsToDomainCount) {
		this.majesticSeoGovReferringDomainsToDomainCount = majesticSeoGovReferringDomainsToDomainCount;
	}


	/**
	 * @return the majesticSeoEduReferringDomainsToDomainCount
	 */
	public BigDecimal getMajesticSeoEduReferringDomainsToDomainCount() {
		return majesticSeoEduReferringDomainsToDomainCount;
	}


	/**
	 * @param majesticSeoEduReferringDomainsToDomainCount the majesticSeoEduReferringDomainsToDomainCount to set
	 */
	public void setMajesticSeoEduReferringDomainsToDomainCount(
			BigDecimal majesticSeoEduReferringDomainsToDomainCount) {
		this.majesticSeoEduReferringDomainsToDomainCount = majesticSeoEduReferringDomainsToDomainCount;
	}


	/**
	 * @return the majesticSeoIPAddressesToDomainCount
	 */
	public BigDecimal getMajesticSeoIPAddressesToDomainCount() {
		return majesticSeoIPAddressesToDomainCount;
	}


	/**
	 * @param majesticSeoIPAddressesToDomainCount the majesticSeoIPAddressesToDomainCount to set
	 */
	public void setMajesticSeoIPAddressesToDomainCount(
			BigDecimal majesticSeoIPAddressesToDomainCount) {
		this.majesticSeoIPAddressesToDomainCount = majesticSeoIPAddressesToDomainCount;
	}


	/**
	 * @return the majesticSeoClassCSubnetsToDomainCount
	 */
	public BigDecimal getMajesticSeoClassCSubnetsToDomainCount() {
		return majesticSeoClassCSubnetsToDomainCount;
	}


	/**
	 * @param majesticSeoClassCSubnetsToDomainCount the majesticSeoClassCSubnetsToDomainCount to set
	 */
	public void setMajesticSeoClassCSubnetsToDomainCount(
			BigDecimal majesticSeoClassCSubnetsToDomainCount) {
		this.majesticSeoClassCSubnetsToDomainCount = majesticSeoClassCSubnetsToDomainCount;
	}


	public String getResultType() {
		return resultType;
	}


	public void setResultType(String resultType) {
		this.resultType = resultType;
	}
}